### ISSUE TITLE
Getting repeated 503 errors from admin

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#1]
Whenever I deploy a stream and later issue a "stream list" command I keep getting 503 errors until first stream module is running

```
dataflow:>stream create ticktock --definition "time | log" --deploy 
Created and deployed new stream 'ticktock'
dataflow:>stream list
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: 503 Service Unavailable

dataflow:>stream list
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: 503 Service Unavailable

```

**Comment by ericbottard** [comment]
Thomas, can you still reproduce this issue?

**Comment by trisberg** [comment]
@ericbottard it's hard to tell, can't deploy the admin app to CF after the latest changes. Getting a DataSource collision:

2016-02-08T10:12:44.68-0500 [APP/0]      ERR Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [javax.sql.DataSource] is defined: expected single matching bean but found 2: mydb,dataSource

I have a MySQL DB bound for the task repository.

**Comment by ericbottard** [comment]
You can always run the admin locally, *targetting* CF.

But, why are there 2 DataSources bound to your admin deploy?

**Comment by trisberg** [comment]
Not relevant any more.
