### ISSUE TITLE
Stream partitions aren't working

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#102]
As a user, I'm trying the following stream with the default partitioning strategy; however, I'm unable to get it working with SCDF's CF server.

**stream:**
```
stream create bar --definition "http | log" 
stream deploy bar --properties "module.http.producer.partitionKeyExpression=payload,module.log.count=2,module.log.partitioned=true"
```

**post:**
```
http post --target http://http.app.cf.apps.io --data 0
http post --target http://http.app.cf.apps.io --data 1
http post --target http://http.app.cf.apps.io --data 2
http post --target http://http.app.cf.apps.io --data 3
http post --target http://http.app.cf.apps.io --data 4
```

**expectation:**
All _odds_ end up in log-instance-1 and the _evens_ at log-instance-0 application logs.

**Comment by markfisher** [comment]
it looks like your missing `consumer` in the property key, e.g.:

```
module.log.consumer.partitioned=true
```

**Comment by sabbyanandan** [comment]
Interesting. The above stream works fine in the Local server, though. Without the `module.log.consumer.partitioned=true` property, that is.

**Comment by ilayaperumalg** [comment]
Actually, you don't need to set the `consumer` property in the consumer app. That `partitioned` property is set at the consumer app once the upstream app is determined to have partitioning properties.

**Comment by markfisher** [comment]
good point @ilayaperumalg - I was thinking about the off-dataflow case

**Comment by sobychacko** [comment]
I ran this test and seeing the results as expected:

`dataflow:>stream create bar --definition "http | log"`
`dataflow:>stream deploy bar --properties "module.http.producer.partitionKeyExpression=payload,module.log.count=2,module.log.partitioned=true"`

`dataflow:>http post --target http://bar-http.local.pcfdev.io --data 0`
`dataflow:>http post --target http://bar-http.local.pcfdev.io --data 1`
`dataflow:>http post --target http://bar-http.local.pcfdev.io --data 2`
`dataflow:>http post --target http://bar-http.local.pcfdev.io --data 3`

**Outcome:**

`2016-05-18T12:35:38.80-0400 [APP/0]      OUT 2016-05-18 16:35:38.805  INFO 18 --- [ar.http.bar-0-1] log.sink                                 : 0`
`2016-05-18T12:35:48.52-0400 [APP/1]      OUT 2016-05-18 16:35:48.525  INFO 14 --- [ar.http.bar-1-1] log.sink                                 : 1`
`2016-05-18T12:35:55.78-0400 [APP/0]      OUT 2016-05-18 16:35:55.782  INFO 18 --- [ar.http.bar-0-1] log.sink                                 : 2`
`2016-05-18T12:36:00.08-0400 [APP/1]      OUT 2016-05-18 16:36:00.085  INFO 14 --- [ar.http.bar-1-1] log.sink                                 : 3`



`

**Comment by markfisher** [comment]
@sobychacko you should probably randomize the numbers a bit to ensure that it's not just happening to align because of round-robin and every other number is even if they're in sequence

**Comment by ilayaperumalg** [comment]
and with our typical way to test this :-)
```
dataflow:>http post --target http://bar-http.local.pcfdev.io --data "How much wood would a woodchuck chuck if a woodchuck could chuck wood"
```

**Comment by markpollack** [comment]
@sabbyanandan What version of SCDF were you running and what PCF environment?

**Comment by sobychacko** [comment]
@markfisher I randomized the test after that with @mbogoevici and it seems like its logging the same data consistently on a specific instance.

**log env properties:**

SPRING_APPLICATION_JSON: {"spring.cloud.stream.bindings.input.destination":"bar.http","spring.cloud.stream.bindings.input.group":"bar"}
count: 2
partitioned: true
spring.cloud.deployer.count: 2
spring.cloud.deployer.group: bar
spring.cloud.stream.bindings.input.consumer.partitioned: true
spring.cloud.stream.instanceCount: 2

**http env properties:**

SPRING_APPLICATION_JSON: {"spring.cloud.stream.bindings.output.producer.requiredGroups":"bar","spring.cloud.stream.bindings.output.destination":"bar.http"}
spring.cloud.deployer.group: bar
spring.cloud.stream.bindings.output.producer.partitionCount: 2
spring.cloud.stream.bindings.output.producer.partitionKeyExpression: payload

**Comment by sabbyanandan** [comment]
Works as expected.

**Comment by sobychacko** [comment]
PR is merged.
