### ISSUE TITLE
How to disable the caching of registered module or force download when re-register module?

### ISSUE THREAD

**Issue by sandip0018** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#109]
@sabbyanandan ,is there any way like we can totally remove registered module from cloud foundry cache or force to re-download module from maven repository?

Thanks,
Sandip

**Comment by sabbyanandan** [comment]
From the Apps tab in`admin-ui`, you can "select all" and "unregister" entries from the application registry. 

![image](https://cloud.githubusercontent.com/assets/1562654/15582188/8a6437e6-2324-11e6-92c6-b12b4f9d8a98.png)

You can always re-register collection of apps listed in a property file via `module import --uri` command. More details [here](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc#register-a-stream-app).

**Comment by sandip0018** [comment]
Hey @sabbyanandan , issue occured when i re-register the module with same version from maven, it not reflected in server, it takes module from cache, not taking latest changes that i have pushed in repository.
can you help on this?

**Comment by sabbyanandan** [comment]
Did you "unregister" all apps? If you didn't, then as described in the [docs](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc#register-a-stream-app), you'd have to use the `--force` option to override pre-existing app.

**Comment by markpollack** [comment]
What maven version are you using for the app?  Is it a build snapshot or are you changing the code and still keeping the same maven version?
