### ISSUE TITLE
Security and OAUTH configuration parameters are missing

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#112]
As a user, I'm trying to configure dataflow-server to connect to UAA running in a PCF instance; however, I'm unable to find the configuration attributes in `dataflow-server.yml`. Similar to local-server, I'd like to have all [security configurations](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-server-local/src/main/resources/application.yml#L24) available for cf-server, too.

**Acceptance:**
- I'm able to enable security for dataflow-server
- I'm able to set OAUTH credentials and successfully negotiate with UAA running in PCF
- CF server docs point to SCDF's core security section

**Comment by markpollack** [comment]
You mean they should be in the yaml for the cf server but commented out?
