### ISSUE TITLE
could not access admin-ui

### ISSUE THREAD

**Issue by sachkk76** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#113]
Recently I pushed spring-cloud-dataflow-server-cloudfoundry-1.0.0.M2 version on PCF. It starts well with embedded tomcat listening on 8080. I am trying access admin-UI url as http://host:8080/admin-ui. it does not recognize the url. Here the host is the value from SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_DOMAIN. Is this something with URL?

**Comment by sabbyanandan** [comment]
In 1.0.0.M2, the dashboard is accessible at `http://<APP_URL>/admin-ui`. The `APP_URL` can be found when you issue `cf apps` command in CF CLI and port routing is handled by CF, so you don't need 8080.

**Example:**
```
→ cf apps
Getting apps in org some-org / space development as someone...
OK

name                    requested state   instances   memory   disk   urls
dataflow-server    started                 1/1             3G            1G    dataflow-server.test.io
```

Dashboard can be accessed at: http://dataflow-server.test.io/admin-ui
