### ISSUE TITLE
Randomized app names

### ISSUE THREAD

**Issue by channing-jackson** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#125]
Just installed and ran the Spring Cloud Data Flow M3 beta, including the MySQL service for registry info.  When I create streams, the resulting PCF apps that get deployed have a randomized application name.  For example, if I create the ticktock stream, my resulting apps might be named like this:

```
dataflow-metallographic-oner-ticktock-time
dataflow-metallographic-oner-ticktock-log
```

I assume this is an attempt to make app names unique across the PCF instance for routing purposes, but is there a way for me to force the name of the apps?

**Comment by sabbyanandan** [comment]
Hi, @channing-jackson: please review the naming convention docs [here](https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry#application-name-settings-and-deployments). Though the randomization is enabled by default, this is overridable at the CF-deployer level. You could configure the right settings (_via: `cf set-env`_) that work for your requirements.

**Comment by markpollack** [comment]
We should add this
