### ISSUE TITLE
datasource hijacking?

### ISSUE THREAD

**Issue by channing-jackson** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#149]
Using spring-cloud-dataflow-server-cloudfoundry-1.0.0.M4

Bound to services: 
redis
mysql
rabbit
spring cloud config server

I have a custom processor module that makes a connection to an external data source through its own Spring Configuration classes.  It comes from its own Spring Boot application, and I'm trying to leverage it in a stream.  Unit and integration tests are working fine, and I'm trying to test a simple stream http | custom-module | log where posting an id to the http source will result in querying our external datasource for the data, and then log it.

Spring Configuration (excerpt)
```
@Bean(name = DataConstants.BEAN_CUSTOM_DATASOURCE)
DataSource customDataSource() { }

@Bean(name = DataConstants.BEAN_VENDOR_ADAPTER) 
JpaVendorAdapter customVendorAdapter() { }

@Bean(name = DataConstants.BEAN_CUSTOM_ENTITY_MGR_FACTORY)
EntityManagerFactory customEntityManagerFactory(JpaVendorAdapter vendorAdapter, DataSource customDataSource) { }
```

Spring Dao (excerpt)
```
@PersistenceUnit(unitName = "customPersistenceUnit")
protected EntityManagerFactory entityManagerFactory; 

public EntityManagerFactory getEntityManagerFactory() { } 

@Autowired
public void setEntityManagerFactory(@Qualifier( DataConstants.BEAN_CUSTOM_ENTITY_MGR_FACTORY) EntityManagerFactory entityManagerFactory) { }
```

What appears to happen when it is deployed is the EntityManagerFactory injected into the Dao is the one from the bound MySQL service instead of the one from my custom Spring configuration.  My queries that should go to the external data source are instead going to the MySQL service, and I'm getting "table does not exist" errors.

---------------------------------
Update: if I unbind the MySQL service from the processor app once it is deployed, and restage it, it works fine.

**Comment by ericbottard** [comment]
I have a gut feeling this is a "simple" Boot app with 2 datasources on PCF issue.
To confirm, could you share your `SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SERVICES` configuration?
If this is indeed the root of the problem, then work ongoing in https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/pull/152 may help

**Comment by channing-jackson** [comment]
SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SERVICES
redis,rabbit,mysql,sccs

**Comment by ericbottard** [comment]
OK, so this is indeed what I thought. Can you confirm that the problem does not happen if you set `SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_SERVICES=redis,rabbit` (I don't know what sccs is), at least for that one deployment.
Also, having those 4 services being *always* bound seems like a lot. I would expect to see only rabbit (your binder) there, the others being specified on a per-deployment basis

**Comment by channing-jackson** [comment]
SCCS is Spring Cloud Config Server. 

I guess I wasn't aware you could customize the bound services on a module-by-module basis.  Would this be done when you define the stream in Spring Cloud Data Flow, or would this be done elsewhere?  Do you have some docs about how to properly bind only the necessary services when defining a stream?

I can confirm that *after* the deployment, if I unbind the MySQL service and restage just that app, the problem goes away.  Is that what you mean, or do you mean that I should customize the bound services for that app in the stream definition?

**Comment by sabbyanandan** [comment]
> Would this be done when you define the stream in Spring Cloud Data Flow, or would this be done elsewhere? Do you have some docs about how to properly bind only the necessary services when defining a stream?

You could optionally pass service binding for each application at the deployment time. For example, if you'd want `mysql` binding for the app `jdbc`, your stream deployment request would be:

> stream deploy jdbcstream --properties "app.jdbc.spring.cloud.deployer.cloudfoundry.services=mysql"

All the common properties applicable at the deployment time are included in the [configuration section](http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.0.0.M4/reference/htmlsingle/#_configuration_reference). And, yeah, there's a typo wrt the property key - we will fix it.

**Comment by sabbyanandan** [comment]
@channing-jackson: Please verify this on [1.0.0.RC1](http://repo.spring.io/libs-milestone/org/springframework/cloud/spring-cloud-dataflow-server-cloudfoundry/1.0.0.RC1/) and if everything is good, we can close this.

**Comment by channing-jackson** [comment]
The additional deployment properties appear to work as prescribed.  I think this issue can be closed now.  Follow-up question, are traditional boot properties also available from that deployment command line?

For example `--properties "app.jdbc.spring.profiles.active=dev"`

Also, in the flo UI when you click the Deploy button, and the deployment dialog appears: 

"Deployment Properties"  I'm assuming you do not need to add the `--properties` portion of the command line statement in there, correct?

**Comment by sabbyanandan** [comment]
> are traditional boot properties also available from that deployment command line?

yes.

> "Deployment Properties" I'm assuming you do not need to add the --properties portion of the command line statement in there, correct?

correct; you'd just add the properties that you need to deploy with the stream. we are in the process of improving the ux around this.

**Comment by channing-jackson** [comment]
Minor Correction: 

After some minor trial and error, the proper syntax would be: 
`app.<appname/label>.SPRING_PROFILES_ACTIVE=dev`
