### ISSUE TITLE
Add canary analysis support using spinnaker

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#150]
As a developer, I'd like to enable the results of a canary style analysis to migrate from v1 to v2 of an app using [spring-cloud-spinnaker](https://github.com/spring-cloud/spring-cloud-spinnaker).

**Acceptance:**
- initial support is to: i) push an app ii) set env-var's iii) change versions
- docs included in the reference guide

**Comment by gregturn** [comment]
To clarify, the actual canary analysis I have demo'd is in spring-cloud-canary (https://github.com/gregturn/spring-cloud-canary. Spring-cloud-spinnaker only installs spinnaker which in turn supports a SpEL expression to invoke some 3rd party service.
