### ISSUE TITLE
Delete of task definition should delete the app in CF

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#155]
As a user, I'd like to delete/destroy the Task from dataflow shell and I want it to actually also delete the app staged in CloudFoundry, too.

**Comment by ericbottard** [comment]
This is blocked by https://github.com/spring-cloud/spring-cloud-deployer/issues/67 IMO

**Comment by ericbottard** [comment]
This should be converted to an SCDF issue IMO, as it's the responsibility of SCDF to call TaskLauncher#destroy accordingly. Following that, the app should now be destroyed, thanks to https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/pull/110

**Comment by ericbottard** [comment]
Closing, core PR is at https://github.com/spring-cloud/spring-cloud-dataflow/pull/1246
