### ISSUE TITLE
Surface character limit errors with the auto-generated routes

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#173]
As a user, I've the `SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_ENABLE_RANDOM_APP_NAME_PREFIX` set to `true`, so I'm able to generate random routes for all the apps. However, when the randomly generated route (_with: host + domain_) name length is beyond the standard 63 characters, the applications fail to stage/start. 

**Findings:**
Cloud Controller returns an error when creating a route with host or domain name that is longer than specified in [RFC 1035](http://www.ietf.org/rfc/rfc1035.txt).

**Acceptance:**
Following error should be propagated all the way to the server logs as well in the shell response.
```
Server error, status code: 400, error code: 210001, message: The route is invalid: host format, host must be no more than 63 characters
```

**Comment by ericbottard** [comment]
I would rather make sure we surface any error appropriately, rather than re-documenting what is itself a CloudFoundry / RFC limitation

**Comment by sabbyanandan** [comment]
Sounds good; I will update the description.

**Comment by sabbyanandan** [comment]
Closing this in favor of https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/89.
