### ISSUE TITLE
Document how to configure CUPS 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#183]
As a user, I'd like to connect to an externally running service such as Kafka and I'd like to refer to the docs on how to configure it in SCDF. 

**Acceptance:**
A new section that includes the steps to configure the server with a custom PCF service.

**Comment by ericbottard** [comment]
Not sure I understand what we want here. Configuration of a UPS is a Cloud Foundry thing, and as such is already documented in Cloud Foundry itself. A UPS is then seen and used as a regular service in CF, so anything that we say in the reference manual for SCDF-CF still applies to a UPS.

If the aim is to document Kafka specifically, then shouldn't we assess the availability of a connector for kafka? Do we have a working env where this is available?

**Comment by sabbyanandan** [comment]
> Configuration of a UPS is a Cloud Foundry thing, and as such is already documented in Cloud Foundry itself.

Agreed. The goal is to have a note in the reference guide about UPS and the fact that it is _possible_ to bind to such services in SCDF orchestrated apps, too. There is no indication of this today and we have had few inquiries. 

> If the aim is to document Kafka specifically, then shouldn't we assess the availability of a connector for kafka? Do we have a working env where this is available?

We have customers using UPS for Kafka and they bind the service with stream apps already. Let's just make sure this is clearly articulated. Not sure we would want to explore the connector option.
