### ISSUE TITLE
Adapt to latest SCDF docs

### ISSUE THREAD

**Issue by ericbottard** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#200]
see https://github.com/spring-cloud/spring-cloud-dataflow/pull/965/files?diff=unified#r85108779

(should only be merged once this server project depends on a post-M2 fixed-version of SCDF)

**Comment by ericbottard** [comment]
This should not have been merged. Sorry, the comment was wrong, we need SCDF POST M2 (I misread the released version at the time)

**Comment by sabbyanandan** [comment]
@ericbottard: SCDF core is already at 1.1.0.M2. Which version are you referring to?

**Comment by ericbottard** [comment]
Something AFTER M2 (need to have https://github.com/spring-cloud/spring-cloud-dataflow/commit/6bb63ffd63396e582194084099e77b7777a83dad in a released version)
