### ISSUE TITLE
Change cf-server POM to inherit from Spring Boot parent

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#202]
As a developer, I'd like to change the cf-server pom.xml to inherit the foundation bits from Spring Boot parent itself. This allows us to capture project metadata, so that we can publish the final artifacts to maven central.

**Comment by trisberg** [comment]
Isn't it `spring-cloud-dataflow-server-cloudfoundry/spring-cloud-dataflow-server-cloudfoundry/pom.xml` that should have a boot parent? Also, seems wrong to have to specify a boot version.

**Comment by ericbottard** [comment]
@trisberg I can not agree more. One more knob to tune at release time and possibility to go out of synch with the rest of the SCDF ecosystem.

PS:  chose to apply to the pom project for consistency. I would really question the benefits if we were to continue inheriting from dataflow parent in one place, and boot parent in the other.

**Comment by markpollack** [comment]
We are going to hold off on this until we can resolve some issues with how to define default application properties in a way consistent with the start.spring.io experience.

**Comment by ericbottard** [comment]
Closing, this is no longer planned
