### ISSUE TITLE
Building CF-server from the starter project does not inherit project metadata

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#207]
As a user, I've downloaded a plain boot application from Spring Initializr and I added the following 2 dependencies, so that I could bootstrap the cf-server with customizations. However, upon running this application locally, I'm unable to get project metadata such as the release version, gh-commit and the name under "About" tab in Dashboard. 

```
<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-starter-dataflow-server-cloudfoundry</artifactId>
	<version>1.1.0.M1</version>
</dependency>
<dependency>
	<groupId>io.projectreactor</groupId>
	<artifactId>reactor-core</artifactId>
	<version>${reactor.version}</version>
</dependency>
```

![image](https://cloud.githubusercontent.com/assets/1562654/20108344/9d01e148-a590-11e6-8d04-8346507a8466.png)

**Acceptance:**
- I can continue to customize cf-server using the starter dependency
- I can see project metadata in the "about" tab (_in dashboard_)

**Comment by ericbottard** [comment]
This has been fixed already
