### ISSUE TITLE
Cannot connect to the server from shell on the latest build

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#209]
As a user, I'm trying to connect to the 1.1.0.BUILD-SNAPSHOT server [commit: 8f8183ce28bc81bfdf2ee31a9b3aab29b28edb49] running on PWS, but I'm getting an NPE.

```
server-unknown:>dataflow config server http://sabby-dataflow-server.cfapps
Unable to contact Data Flow Server at 'http://sabby-dataflow-server.cfapps': 'java.lang.NullPointerException'.
```

**Comment by sabbyanandan** [comment]
With further trials, it looks like this is problem in shell. I could connect to the same server instance using 1.1.0.M1 release of shell. The latest shell release only works with local-server. 

```
> java -jar spring-cloud-dataflow-shell-1.1.0.M1.jar
server-unknown:>dataflow config server http://sabby-ci-dataflow-server.cfapps
Successfully targeted http://sabby-ci-dataflow-server.cfapps
```

**Comment by ericbottard** [comment]
You're not actually running what you think you're running as a server: it lacks the task completion endpoint.
```
curl http://sabby-dataflow-server.cfapps.io/ | json_pp | grep comp

      "completions/stream" : {
         "href" : "http://sabby-dataflow-server.cfapps.io/completions/stream{?start,detailLevel}",


curl localhost:9393 | json_pp | grep comp
      "completions/stream" : {
         "href" : "http://localhost:9393/completions/stream{?start,detailLevel}",
      "completions/task" : {
         "href" : "http://localhost:9393/completions/task{?start,detailLevel}"
```

Please re-open if I'm missing something

**Comment by sabbyanandan** [comment]
The cf-server is pulling [core] RC1 release bits and I'm still unable to connect with the RC1 release of the shell application. Is it working for you?

**Comment by ericbottard** [comment]
I am
Let's debug this together tomorrow

Le 14 nov. 2016 8:49 PM, "Sabby Anandan" <notifications@github.com> a
écrit :

**Comment by sabbyanandan** [comment]
I've been having some odd local maven caching situation that might have caused this glitch. With a clean cache, new build, and upon deployment to CF, I'm able to connect to the server successfully.
