### ISSUE TITLE
Test 1.1.x server on PCF 1.7, 1.8, and 1.9

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#222]
As a PM, I'd like to test the upcoming release on PCF 1.7, 1.8, and 1.9 releases. 

Test simple streams and tasks in:
- [x] PCF 1.7
- [x] PCF 1.8
- [x] PCF 1.9

**Comment by viniciusccarvalho** [comment]
Test

**Comment by sabbyanandan** [comment]
The scope of this story is complete. Thanks to @ericbottard @viniciusccarvalho, and @markpollack!
