### ISSUE TITLE
Add docs on how to delete tasks in PCF

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#223]
Since there isn't any direct way to delete a Task via CF CLI, as a workaround, we should document how to delete it via REST calls.

**Comment by ericbottard** [comment]
I don't get this. There should not be any CF specific deletion

**Comment by sabbyanandan** [comment]
There's no API to delete a Task from CF CLI, yet. We would have do CURL commands to delete the bound services and then the Task. The scope is to document just that.

**Comment by ericbottard** [comment]
But `task destroy foo` will ultimately do that

**Comment by sabbyanandan** [comment]
Multiple items we discussed in the IPM that might clear things up. Let's sync-up when you're back.

**Comment by trisberg** [comment]
@ericbottard yes, `task destroy` will ultimately do the deleting but for now (the 1.1.0 GA release) we rely on deleting the task executions and the app using the CLI. When we implement the delete features for the next release we can remove these instructions.
