### ISSUE TITLE
Document setting TASK_SERVICES in getting started docs

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#231]
Add `cf set-env dataflow-server SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_SERVICES my_mysql` to the  list of env-vars to set 

also show how to register and run the timestamp task in the getting started section.

**Comment by cppwfs** [comment]
I did a build of the docs locally and the using `./mvnw clean package -DskipTests -P full -pl spring-cloud-dataflow-server-cloudfoundry-docs -am`  and I see where section 41.2-41.4 covers that topic.

**Comment by trisberg** [comment]
It's also covered in "Part VII. Tasks on Cloud Foundry"? Having this content spread out over multiple chapters/sections is confusing.
