### ISSUE TITLE
Update Reactor dependency

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#241]
As a developer, I'd like to update `reactor` core dependency to 3.0.4.RELEASE.

**Acceptance:**
- Reactor core is updated to 3.0.4.RELEASE
- Build + tests run successfully
- Docs updated

**Comment by ericbottard** [comment]
Addressed by https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/pull/237

**Comment by markpollack** [comment]
https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/commit/d27d1887c48ac587eeef4b7016502a3c2ce66b2b
