### ISSUE TITLE
Remove "spring-cloud-services-starter-config-client" instruction from docs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#258]
As a developer, I'd like to remove the references of `spring-cloud-services-starter-config-client` requirement from the docs, because we already include it as a default dependency.

**Comment by ericbottard** [comment]
See https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/search?utf8=%E2%9C%93&q=spring-cloud-services-starter-config-client

This HAS been removed
