### ISSUE TITLE
Dataflow shell import error

### ISSUE THREAD

**Issue by vishukadam** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#280]
Hi, 
I am new to spring cloud stream and trying develop streambase application (time-processor- sink) with Kafka. I using Spring boot 1.4.5 and dataflow 1.1.0 release. While importing the in dataflow shell i get following error:   
dataflow:>app import --uri https://bit.ly/Avogadro-SR1-stream-applications-kafka-10-maven
I get the following error.
Command failed java.lang.IllegalArgumentException: java.net.ConnectException: Connection timed out: connect.
If i hit the URL from browser it download a file "spring-cloud-stream-app-descriptor-Avogadro.SR1"
But from the dataflow shell prompt gives error

**Comment by trisberg** [comment]
Could you try using `http` like - `http://bit.ly/Avogadro-SR1-stream-applications-kafka-10-maven`

**Comment by ericbottard** [comment]
Also, where are your server and shell running, respectively? Are they behind any equipment that could prevent them from accessing this URL?

**Comment by vishukadam** [comment]
Dataflow server and shell are on the local machine. I found a workaround using  file. I downloaded the file from the URL and register the application using fie://......
