### ISSUE TITLE
Dataflow server jar URL incorrect in docs

### ISSUE THREAD

**Issue by jldec** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#281]
http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.2.0.M1/reference/htmlsingle/#_download_the_spring_cloud_data_flow_server_and_shell_apps

the first link says 

http://repo.spring.io/milestone/org/springframework/cloud/spring-cloud-dataflow-server-cloudfoundry/1.2.0.M1/spring-cloud-dataflow-server-cloudfoundry-1.2.0.M1.jar

but the release is actually in 

http://repo.spring.io/release/org/springframework/cloud/spring-cloud-dataflow-server-cloudfoundry/1.2.0.M1/

not sure if the issue is a mistake in the docs or with the repo location of the release.

**Comment by ericbottard** [comment]
Good catch, M1 was promoted in the wrong sub-repo. I (tried to) fixed it, may take some time to actually be witnessed. Let's keep this open for now

**Comment by ericbottard** [comment]
Fixed, thanks!

**Comment by jldec** [comment]
✨  awesome - thank you @ericbottard !
