### ISSUE TITLE
Using data flow with https on cloud foundry

### ISSUE THREAD

**Issue by BLaurent** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#293]
Hi,

I trying to deploy a data flow server on Cloud foundry.
Only https end point could expose, and I cannot enable https using this : 
http://docs.spring.io/spring-cloud-dataflow/docs/current-SNAPSHOT/reference/htmlsingle/#configuration-security-enabling-https
As ssl is managed by cf. How do I make data flow server using https?

Thanks in advance.
Best Regards

**Comment by markpollack** [comment]
What version of SCDF are you using?

**Comment by BLaurent** [comment]
Hi Mark,
I solved this issue, yml configuration was not correct.
Thanks
