### ISSUE TITLE
Link to Spring Cloud Task Reference guide is incorrect

### ISSUE THREAD

**Issue by wxlund** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#298]
> 3. Spring Cloud Task

Spring Cloud Task makes it easy to create short-lived microservices. We provide capabilities that allow short-lived JVM processes to be executed on demand in a production environment.

For more details about the core framework components and the supported features, please review Spring Cloud Task’s reference guide.

There’s a rich ecosystem of Spring Cloud Task Application-Starters that can be used either as standalone microservice applications or in Spring Cloud Data Flow. For convenience, the generated application-starters are available for use from Maven Repo. There are several samples available for reference.>

The link to the Spring Cloud Task reference is a 404. [http://docs.spring.io/spring-cloud-task/1.1.2.RELEASE/reference/htmlsingle/](http://docs.spring.io/spring-cloud-task/1.1.2.RELEASE/reference/htmlsingle/) 

I think 1.1.1.RELEASE is what was meant as it works but not sure.

**Comment by ericbottard** [comment]
Link is actually missing a `/docs/` part in there somewhere. Thanks for spotting this out

**Comment by ericbottard** [comment]
Fixed via bbe9f73
