### ISSUE TITLE
Remove the inclusion of cloud-config-client dependency section from the docs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#300]
As a developer, I'd like to remove the section on [`16.2.1. Stream, Task, and Spring Cloud Config Server`](http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.2.0.M2/reference/htmlsingle/#_stream_task_and_spring_cloud_config_server) from the reference guide. 

Note: With https://github.com/spring-cloud-stream-app-starters/app-starters-release/issues/80, we are now adding this dependency to all the OOTB apps by default.

**Comment by ericbottard** [comment]
what about custom apps that are not coming from starters?
