### ISSUE TITLE
Wrong spring-core version included

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#314]
The latest server build has the wrong `spring-core-4.3.6.RELEASE.jar` included, all other spring jars are 4.3.7. Had same issue for the k8s server and fixed it temporarily with this commit in the deployer - https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/commit/795d60313c75b20d3f25f203c4f4353e93d85699

**Comment by trisberg** [comment]
There is a long-term solution in the works in spring-cloud-build (https://github.com/spring-cloud/spring-cloud-build/commit/d4257bc99c92cb0b6afdea843803aec592346bd5) but until then adding a `spring-context` dependency in the deployer seems like the least intrusive fix.

**Comment by ericbottard** [comment]
Thanks @trisberg.
Will fix

**Comment by markpollack** [comment]
Fixed in spring-cloud-build 1.3.8
