### ISSUE TITLE
Stream Deployment on PCF has random strings appended

### ISSUE THREAD

**Issue by rahulvijay24feb** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#338]
Hi,
While I am trying to deploy a stream called DrugSizeTest with a dataingestorSize source and a log sink. I get a random string appended each time i recreate and deploy the stream - In the current case "supercausal" . 

dataflow-supercausal-detent-DrugSizeTest-dataingestorSize
dataflow-supercausal-detent-DrugSizeTest-log

This is making the url of the rest service exposed on dataingestorSize change for each deployment. Am i missing something here ? Do we have an alternative for this ?

**Comment by ilayaperumalg** [comment]
Hi,

The optional random name is prefixed to the app name by the CF deployer by default. To disable this, you can do:

```
cf set-env <dataflow-server-name> 
SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_ENABLE_RANDOM_APP_NAME_PREFIX false
```

**Comment by rahulvijay24feb** [comment]
Saves my Day ! Thank you :+1:
