### ISSUE TITLE
Input Channel not being being established.

### ISSUE THREAD

**Issue by leodacosta4214** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#340]
Hi,  I follow this [source ](http://engineering.pivotal.io/post/spring-cloud-data-flow-sink/) for trying out a custom data sink. I see that it receives no message. Logs specify that there was no subscriber to input channel while the only subscriber created was for the error channel. Is there a compatibility issue here  ?

**Comment by rahulvijay24feb** [comment]
Faced similar issue. Please follow the answer from @sabbyanandan . Confirm if you are importing the configuration file in your app.


Reference : https://stackoverflow.com/questions/44457901/input-channel-subscriber-not-up-for-custom-sink-in-spring-cloud-data-flow

**Comment by leodacosta4214** [comment]
Hi,

Thank you for the reply. Worked by importing the configuration class. Thank you.
