### ISSUE TITLE
Prefix dataflow server unique ID and stream name to the name of deployed applications

### ISSUE THREAD

**Issue by making** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#35]
I'm trying SCDF Admin CloudFoundry 1.0.0.M1

Stream name seems to have to be unique in the same domain. 

Otherwise 400 error will return as follows:

``` console
dataflow:>stream create --name ticktock --definition "time | log" --deploy
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: 400 Bad Request

400 Bad Request

org.springframework.cloud.dataflow.rest.client.DataFlowClientException: 400 Bad Request

    at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:52)
    at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
    at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:357)
    at org.springframework.cloud.dataflow.rest.client.StreamTemplate.createStream(StreamTemplate.java:79)
    at org.springframework.cloud.dataflow.shell.command.StreamCommands.createStream(StreamCommands.java:99)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216)
    at org.springframework.shell.core.SimpleExecutionStrategy.invoke(SimpleExecutionStrategy.java:64)
    at org.springframework.shell.core.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:57)
    at org.springframework.shell.core.AbstractShell.executeCommand(AbstractShell.java:130)
    at org.springframework.shell.core.JLineShell.promptLoop(JLineShell.java:533)
    at org.springframework.shell.core.JLineShell.run(JLineShell.java:179)
    at java.lang.Thread.run(Thread.java:745)
```

Is it correct? Actually, it was success when `ticktock-foo` was used as the stream name, which may not be taken.

I think it's so inconvenient. Can we use `--random-route` to escape duplication of the name? 

My memo is [here](https://github.com/making/blog.ik.am/blob/spring-cloud-data-flow/content/_spring-cloud-data-flow.md#deploy-admin-on-cloud-foundry).

**Comment by ericbottard** [comment]
`--random-route` is an idea. But I thihk the general consensus is that you'd use a dedicated domain for your deployments, thus avoiding any conflict in the first place.

I also wished we could report a better error message, but I'm afraid the info is not available. I'll look into it

**Comment by sabbyanandan** [comment]
@ericbottard: After talking to @nebhale, it is possible to rely on [`CloudFoundryException.getCode()`](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-client/src/main/java/org/cloudfoundry/client/v2/CloudFoundryException.java#L63) API to get the code and then derive user-friendly messages for `dataflow-server` and its clients. 

CF V2 API errors and description are listed [here](https://docs.cloudfoundry.org/running/troubleshooting/v2-errors.html). Perhaps for the above scenario, we may be receiving `100002` (i.e: _AppNameTaken_). 

Note: 
- what we receive from the `cf-java-client` would be app or service centric; generally anything coming from the runtime itself, so we may have to derive the description that is `dataflow-server` friendly.  
- revisit the list of error codes once CAPI V3 is released

**Comment by markpollack** [comment]
I suggest that we introduce the notion of a Data Flow server prefix that would be a prefix to the stream name + application name.  This would decrease the chance that when people follow a getting started guide with the 'ticktock' stream name, they will use an existing route. 

One would still have the same issue if there were two data flow servers installed with the same prefix name, but that maybe easier to control.  We could create the name by default to something cute+random much like random-route is now, but would allow for better discovery/grouping of apps as they would be more consistently named.  

So deploying ticktock would have `dfPurple.ticktock.time` and `dfPurple.ticktock.log` as application/route names for one user and `dfYellow.ticktock.time` and `dfYellow.ticktock.log` for another user that has dataflow server installed in the same org (but different spaces).

**Comment by markpollack** [comment]
Why do we use a dash instead of a dot to separate parts of the name. Turns out Kubernetes doesn't like dashs in application names, so if there isn't a compelling reason to use a dash, can we switch to a dot.

**Comment by sabbyanandan** [comment]
@ericbottard suggests we could manage the uniqueness of the `route` just by the virtue of having a different `domain` associated with each dataflow-server instance. 

This would mean, prior to provisioning dataflow-server instance (_using the tile_), we would also create a custom domain for this instance. This can be created and set as env-var if you're pushing it as standalone application, too. 

For example: If the situation warrants 2 instances of dataflow-server and they can be customized to be provisioned with `mpollack.navy.springapps.io` and `eric.navy.spring.apps.io` respectively. 

With this your routes for `foo=http | log` stream would then be:

```
foo.http.mpollack.navy.springapps.io
foo.log.mpollack.navy.springapps.io
```
and

```
foo.http.eric.navy.springapps.io
foo.log.eric.navy.springapps.io
```

Hence, they wouldn't conflict anymore.

**Comment by markpollack** [comment]
As per some offline discussion, the domain approach was rejected by CF team as being too heavy handed.  The approach we settled on was to have the dataflow server generate a unique ID and prefix the already 'ticktock.time' app with something unique.  Instead of a UUID, this can be a unique word generator to make it it look at bit more appealing to app listings.

**Comment by markpollack** [comment]
@ericbottard Just coming back to this wrt to why random-route would not work.  I don't see a difference between telling PCF to create a random-route and us creating it ourselves.  I just dusted off my PWS account and ran the demo

```
[9:01:54 AM] Mark Pollack: applications:
- name: cf-spring
  memory: 512M
  instances: 1
  random-route: true
[9:02:16 AM] Mark Pollack: This resulted in Creating route cf-spring-nonorthographic-pentarchy.cfapps.io...
OK

Binding cf-spring-nonorthographic-pentarchy.cfapps.io to cf-spring...
```

If we deployed ticktock then we would have  ticktock-time-<random-word-1>-<random-word-2> and so on.  ATM we were thinking of <username>-<random-5-letters>-ticktock-time.

Thoughts?

**Comment by nebhale** [comment]
As a datapoint, the random route functionality is implemented by clients, not servers; both the CF CLI and the [CF Java Client](https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-operations/src/main/java/org/cloudfoundry/operations/applications/WordListRandomWords.java) do this.  So, if you wanted to manage random-ness in SCDF, then there's no real down-side to it.

**Comment by markpollack** [comment]
ah, sweet - maybe we can snag that code from the Java Client.  The username in a PCF install is unique, so that seems like a good prefix/suffix to ensure uniqueness across routes.  Thoughts on using username?

**Comment by ericbottard** [comment]
My concern was that if it was truly random, it would not be predictable, which would make chaining things impractical (like tests).

**Comment by markpollack** [comment]
there would always be a property to specify it, so for tests say.  But by default the user wouldn't have to set that which would avoid the most common case we get of everyone calling their stream "ticktock" or "ticktock1" in some attempt to be unique...

**Comment by gregturn** [comment]
I'm sure with a property (a switch of sorts) this can be easily testable.
