### ISSUE TITLE
Config-server section is missing from 1.2.3 and 1.3.x docs

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#352]
As a user, I'm trying to find the config-server docs in the latest reference guide, but it is not included. It shows up in [1.2.2.RELEASE docs](http://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.2.1.RELEASE/reference/htmlsingle/#_stream_task_and_spring_cloud_config_server).

This [commit](https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/commit/24e6f3debecfc8689de522c692a71d0df28c76a6) seems to have caused the anomaly.

**Comment by ericbottard** [comment]
The aforementioned commit was lacking [this important part](https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/commit/9c1cd6737933b11bdebf5cb626d46398ed97df45).

Backporting as well
