### ISSUE TITLE
Question: Service Binding

### ISSUE THREAD

**Issue by rahulvijay24feb** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#353]
Question : How would we bind services to the stream apps deployed through SCDF server on cloud foundry ? Is there an option to feed in manifest for the registered apps ?

**Comment by ericbottard** [comment]
You can bind services to _every stream app_ via `SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_SERVICES` as documented [here](https://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/current-SNAPSHOT/reference/htmlsingle/#_configuration_reference), and in addition to that, you can bind services on a _per app basis_, as documented [here](https://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/current-SNAPSHOT/reference/htmlsingle/#getting-started-service-binding-at-application-level).

**Comment by rahulvijay24feb** [comment]
That helped me. Thank you Eric.
