### ISSUE TITLE
One-off task support

### ISSUE THREAD

**Issue by jvmlet** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#390]
Hello
Does SCDF for CF integrates the `one-off` task invocation feature, during deployment, for example?
If not, what is the workaround for not having `one-off` task be ran manually each time the new version of my custom task is  released?

**Comment by sabbyanandan** [comment]
Please review ["Tasks on Cloud Foundry"](https://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.3.0.RELEASE/reference/htmlsingle/#tasks-on-cloudfoundry) section from the reference guide. Also, for questions, it'd be better to use StackOverflow or gitter going forward.
