### ISSUE TITLE
Review master branch for backports to 1.4.1.RELEASE

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#411]
* Should update versions of cf deployer to latest  (fix related to CF tile needs)
* Doc changes should get pulled in

Does not seem there are any significant code changes.

**Comment by ilayaperumalg** [comment]
Back ported the changes and pushed them into https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/tree/1.4.x
