### ISSUE TITLE
Update connector library to support configuration of Hikari CP

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#415]
See https://github.com/spring-cloud/spring-cloud-dataflow/issues/2234 for more details.

**Comment by jvmlet** [comment]
@markpollack, as I understand, the CP configuration would be done via environment variable? Is it SPRING_DATASOURE or SPRING_DATASOURE_HIKARI prefix? Would you please update documentation as well with some examples.
Thanks
