### ISSUE TITLE
Document Scheduler integration

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#424]
As a developer, I'd like to document the integration of PCF Scheduler + SCDF, so it'd help the users to follow along, configure, and set it up for use.

Depends on screenshots via spring-cloud/spring-cloud-dataflow#297.

**Acceptance:**
- Document configuration properties exposed via SCSh-CF-Scheduler and/or CF-Deployer
- Include a sample manifest showing the new properties 
- Include a new section that delves into the specifics of architecture with a simple block diagram
- Link to Dashboard screenshots from the core docs via spring-cloud/spring-cloud-dataflow#297

**Comment by cppwfs** [comment]
:thumbsup:
