### ISSUE TITLE
Prepare for 1.7.2.RELEASE

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#454]
As part of the 1.7.2.RELEASE, prepare the following.

- [x] Bump SCDF core to 1.7.2.RELEASE
- [x] Check CFJC/Reactor releases

**Comment by ilayaperumalg** [comment]
Didn't find the latest CFJC/Reactor release as `1.1.0.RELEASE` is the latest.
