### ISSUE TITLE
Remove default OAuth2 configurations 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#461]
As a developer, as part of ongoing security consolidation on 2.0 line, I'd like to remove the default OAuth2 configurations from the bundled JAR. If someone wants to enable it, they would have to explicitly configure the required properties.

child of spring-cloud/spring-cloud-dataflow#2574

**Comment by sabbyanandan** [comment]
We will also have to remove the default security configurations from the ref. guide.

**Comment by ghillert** [comment]
Added some clarification with commit https://github.com/spring-cloud/spring-cloud-dataflow-server-cloudfoundry/commit/06a5125739ae82aa089652894cfc76e934c0137d
