### ISSUE TITLE
Default apps registry populator property needs to be set

### ISSUE THREAD

**Issue by ilayaperumalg** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#89]
I believe CF server needs something like this:
https://github.com/spring-cloud/spring-cloud-dataflow-server-mesos/blob/master/spring-cloud-dataflow-server-mesos/src/main/resources/dataflow-server.yml#L23

**Comment by sabbyanandan** [comment]
The latest on this is to start all the deployer variants with an empty registry. With that, we wouldn't need the placeholder for properties file either, so the CF deployer is good. Mesos and Kubernetes needs to remove the empty file and the YAML reference.
