### ISSUE TITLE
No route URL is created

### ISSUE THREAD

**Issue by sachkk76** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#90]
cf push myapp --no-start -b java_buildpack_offline  spring-cloud-dataflow-server-cloudfoundry-1.0.0.BUILD-SNAPSHOT.jar
With this command I get below message while deploying spring-cloud-dataflow-server on cf
"App myapp is a worker, skipping route creation"

I need route url so that can connect from local shell. Even I tried giving domain/hostname/route path options, it didn't work. Also tried cf create-route after starting application but no luck

**Comment by sabbyanandan** [comment]
Hi, @sachkk76:

Thanks for reporting. 

Could you please confirm (i) whether you've followed the [instructions](http://docs.spring.io/spring-cloud-dataflow-admin-cloudfoundry/docs/current-SNAPSHOT/reference/htmlsingle/#getting-started) in entirety and (ii) that you're able to push any other app successfully with the custom `java_buildpack_offline`? Also, what version of [java-buildpack](https://github.com/cloudfoundry/java-buildpack/releases) are you basing yours on?

If you could also share the entire stacktrace of the `dataflow-server-cloudfoundry` application, it'd be helpful.

**Comment by sachkk76** [comment]
Thanks @sabbyanandan on quick response. 
- Yeah I have followed the instruction as given
- This is the 1st app I had tried pushing and it ran successfully except no routing url 
- version - java-buildpack-offline-v3.5.1.zip

**Comment by sabbyanandan** [comment]
Thanks for the details. If you're able to successfully run the server, where do you see `"App myapp is a worker, skipping route creation"` message? Do you have more stacktrace associated with this message?

**Comment by sachkk76** [comment]
So this when I run below command on CLI
C:\cloudfoundry>cf push myapp --no-start -p spring-cloud-dataflow-server-cloudfoundry-1.0.0.BUILD-SNAPSHOT.jar
Following logs are printed - 

Using manifest file C:\cloudfoundry\manifest.yml
Updating app myapp in org myorg / space dev as xyz...
OK
App myapp is a worker, skipping route creation
Uploading spring-cloud-dataflow-server...
Uploading app files from: C:\Users\xyz\AppData\Local\Temp\unzipped-app111576419
Uploading 2M, 146 files
Done uploading
OK
Binding service myredis to app myapp in org myorg / space dev as xyz...
OK

**Comment by sabbyanandan** [comment]
It seems like the `manifest.yml` file is taken precedence in your case. 

Did you build the latest code from `master` branch and you've the file `spring-cloud-dataflow-server-cloudfoundry-1.0.0.BUILD-SNAPSHOT.jar` available under `C:\cloudfoundry` folder? 

It'd be better to move the `spring-cloud-dataflow-server-cloudfoundry-1.0.0.BUILD-SNAPSHOT.jar` elsewhere and retry push.

**Comment by sachkk76** [comment]
So I am not building it from master branch. I have downloaded from http://repo.spring.io/snapshot/org/springframework/cloud/spring-cloud-dataflow-server-cloudfoundry/1.0.0.BUILD-SNAPSHOT/spring-cloud-dataflow-server-cloudfoundry-1.0.0.BUILD-SNAPSHOT.jar

**Comment by sachkk76** [comment]
Following settings in .yml file fixed this issue.
  no-route: false
  no-hostname: false
  health-check-type: 'none'
