### ISSUE TITLE
Not able to register module on data flow server deployed on cloud foundry

### ISSUE THREAD

**Issue by sachkk76** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#92]
I am trying connect to spring cloud data flow server deployed on CF from local data flow shell
This is how I go and could connect to data flow REST end point from local shell

server-unknown:>dataflow config server https://spring-cloud-dataflow-server.xyz.com
Successfully targeted https://spring-cloud-dataflow-server.xyz.com

Then when I tried register a module its throws error - 
dataflow:>module register --name abcSource --type source --coordinates com.xyz.cloud:abc-soure:jar:exec:1.0.0-SNAPSHOT
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Required String parameter 'uri' is not present

Required String parameter 'uri' is not present
org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Required String parameter 'uri' is not present
  at org.springframework.cloud.dataflow.rest.client.VndErrorResponseErrorHandler.handleError(VndErrorResponseErrorHandler.java:52)

I think module command do not have uri option.
This works good with cloud data flow server local.

**Comment by sabbyanandan** [comment]
Hi, @sachkk76: 

We have moved away from `--coordinates` and it is replaced with `--uri` property across all the server variants. Though SCDF's CF server is at 1.0.0.M2, SCDF's core bits (_including shell_) is at 1.0.0.M3 release - check out the release trains in the [project site](http://cloud.spring.io/spring-cloud-dataflow/). So, make sure you're running 1.0.0.M3 release of the shell locally. 

Now, for your situation, you'd have to register the apps as described in the [docs here](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc#register-a-stream-app). The qualifier `:exec` is also not necessary anymore. Depending on the message bus of choice, you'd need to register the respective apps. Alternatively, you could bulk import using the `module import` command. 

For instance, if you're using `rabbit` as the message, you'll be registering the app like:
```
module register --name jdbc --type sink --uri maven://org.springframework.cloud.stream.app:jdbc-sink-rabbit:1.0.0.M1 --force
```
(_notice the binder type: `jdbc-sink-**rabbit**`_)

**Comment by sachkk76** [comment]
Thanks @sabbyanandan 
I would upgrade to newer version but for now I am rolling around same issue as could see below

dataflow:>module register --name abcSource --type source --coordinates com.xyz.cloud:abc-soure:jar:exec:1.0.0-SNAPSHOT
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: Required String parameter 'uri' is not present

dataflow:>module register --name abcSource --type source --uri maven://com.xyz.cloud:abc:jar:1.0.11-SNAPSHOT
You should specify option (--coordinates, --force) for this command

dataflow:>module register --name abcSource --type source --uri maven://com.xyz.cloud:abc:1.0.11-SNAPSHOT --force true
You should specify option (--coordinates) for this command

Now if add coordinate to above command it says - 
Option 'uri' is not available for this command. Use tab assist or the "help" command to see the legal options

I am not sure why for spring-cloud-dataflow-server-cloudfoundry-1.0.0.BUILD-SNAPSHOT.jar version 
command 
module register --name abcSource --type source --coordinates com.xyz.cloud:abc-soure:jar:exec:1.0.0-SNAPSHOT is not working when it worked well in local. 
is this URI mean to be data flow sever REST end point in CF?

Sorry for long message.

**Comment by sabbyanandan** [comment]
If you're on SNAPSHOT, please use SNAPSHOT version of local/cf servers and as well as the shell. Make sure you either build the project or download the *latest* SNAPSHOT versions. The compatibility between servers and the shell is the key.

Also, as pointed out in previous comment, you're still using `:exec` token while registering the app and that is wrong. See [here](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/streams.adoc#register-a-stream-app).

**Comment by sachkk76** [comment]
I downloaded 1.0.0.M3 for shell it worked. So I have spring-cloud-dataflow-server-cloudfoundry-1.0.0.BUILD-SNAPSHOT.jar on CF and spring-cloud-dataflow-shell-1.0.0.M3.jar as local shell. 
Now getting error in stream creation - 
OUT Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.springframework.cloud.stream.module:log-sink:jar:1.0.0.BUILD-SNAPSHOT from/to repository1 (https://xyz.com/nexus/content/repositories/snapshots/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.
So where do I install certificate on CF? Do I have to specify in env? Does Pivotal App manager UI provides me a way to install certificates?

**Comment by ilayaperumalg** [comment]
@sachkk76 While the `https` requires auth in this case which needs to be addressed either by specifying authentication for the `xyz.com` , do you have problem using `http://` instead for your maven repository?

**Comment by sachkk76** [comment]
My repo do require authentication and could pass certs path when I did setup this on local.. so I was trying similar on cloud foundry.. so not sure I how do I set up this on CF

**Comment by sabbyanandan** [comment]
@sachkk76: Is this still a problem?

**Comment by sachkk76** [comment]
It was certs issue, so we got build pack with certs within resolved the issue. So now could create stream on CF. will close this issue
