### ISSUE TITLE
Maven artifact connect issue with spring-cloud-dataflow-server-local-1.0.0.M3 version

### ISSUE THREAD

**Issue by sachkk76** [spring-cloud/spring-cloud-dataflow-server-cloudfoundry#94]
Hi,
With MAVEN_REMOTE_REPOSITORIES setting and other required maven setting I could connect to remote maven repo with spring-cloud-dataflow-server-local-1.0.0.BUILD-SNAPSHOT.
 Recently I have upgraded to spring-cloud-dataflow-server-local-1.0.0.M3. I am getting issue while getting maven artifacts when trying to deploy stream and with module info command. Any maven setting that has changed from earlier version to 1.0.0.M3?

java.lang.IllegalStateException: failed to resolve MavenResource: com.xyz: abc :jar:1.0.0-SNAPSHOT
        at org.springframework.cloud.deployer.resource.maven.MavenArtifactResolver.resolve(MavenArtifactResolver.java:238) ~[spring-cloud-deployer-resource-maven-1.0.0.M1.jar!/:1.0.0.M1]
        at org.springframework.cloud.deployer.resource.maven.MavenResource.getInputStream(MavenResource.java:164) ~[spring-cloud-deployer-resource-maven-1.0.0.M1.jar!/:1.0.0.M1]
        at org.springframework.cloud.deployer.resource.support.DelegatingResourceLoader.getResource(DelegatingResourceLoader.java:111) ~[spring-cloud-deployer-resource-support-1.0.0.M1.jar!/:1.0.0.M1]
        at org.springframework.cloud.dataflow.registry.AppRegistration.getResource(AppRegistration.java:101) ~[spring-cloud-dataflow-registry-1.0.0.M3.jar!/:1.0.0.M3]
        at org.springframework.cloud.dataflow.server.controller.ModuleController.info(ModuleController.java:115) ~[spring-cloud-dataflow-server-core-1.0.0.M3.jar!/:1.0.0.M3]

Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact com.xyz: abc :jar:1.0.0-SNAPSHOT from/to repository1 (<some repo url>): Connection refused: connect
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444) ~[aether-impl-1.0.2.v20150114.jar!/:na]
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246) ~[aether-impl-1.0.2.v20150114.jar!/:na]

Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_73]
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_73]

**Comment by sabbyanandan** [comment]
As discussed in the other issue [#92], could you double check your application's `--uri` coordinates? Perhaps also share the `module register` command here.

**Comment by sachkk76** [comment]
module register --name pqr --type source --uri maven://com.xyz:abc:jar:1.0.0-SNAPSHOT

**Comment by sabbyanandan** [comment]
There's no change to the maven settings with the M3 release. The thing that changed however, is the application registration workflow. 

- Is this an OOTB or custom stream application?
- If it is a custom application, do you have this JAR with the above `group-id`, `artifact-id`, and `version` combination in your repo? Quick validation would be to resolve it as a maven dependency using a sample project. (_i.e: add it as a maven dependency and see whether the sample project downloads the dependency and builds successfully_)

**Comment by sachkk76** [comment]
Its custom app. The error hints me that for some reason its not connecting maven repo (Caused by: java.net.ConnectException: Connection refused: connect) With same maven setting and jar I was successful (locally) with 1.0.0 version. So now with m3 version the only change is coordinate, we are using uri for app maven artifacts.

Mean while I also tried existing app as well.

dataflow:>module info source:time
Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: failed to resolve MavenResource: org.springframework.cloud.stream.app:time-source-kafka:jar:1.0.0.M1
failed to resolve MavenResource: org.springframework.cloud.stream.app:time-source-kafka:jar:1.0.0.M1
org.springframework.cloud.dataflow.rest.client.DataFlowClientException: failed to resolve MavenResource: org.springframework.cloud.stream.app:time-source-kafka:jar:1.0.0.M1

what is OOTB?

Also gone though spring-cloud-deployer / spring-cloud-deployer-resource-maven which does not seem to be changed.

**Comment by sabbyanandan** [comment]
The change from `--coordinates` to `--uri` shouldn't impact. We intentionally modified the property to be more generic, because we now support `maven`, `docker`, `file`, `http`, and `hdfs` for application artifact resolutions.

It's confusing that you're posting errors from `Local` server. This repo is for SCDF's CloudFoundry server. Are you running the Local or CF server? If Local, it'd be better we track the issue on SCDF's [Local repo](https://github.com/spring-cloud/spring-cloud-dataflow/tree/master/spring-cloud-dataflow-server-local) and close the issue here.

It is starting to look like your maven repo is behind the proxy and it is not correctly configured - review the settings [here](https://github.com/spring-cloud/spring-cloud-dataflow/blob/master/spring-cloud-dataflow-docs/src/main/asciidoc/getting-started.adoc#deploying-local). Follow the conversation [here](https://github.com/spring-cloud/spring-cloud-dataflow/pull/439) for more background.

**Comment by sachkk76** [comment]
Sorry for confusion. With m3 version I was trying on local first and then CF.

**Comment by sachkk76** [comment]
There was java build pack issue. its working now.. so could deploy apps on CF. 
I have groovy transform app which uses groovy script, when deployed stream with this groovy transform module, getting below error - 
ERR [Buildpack] ERROR Compile failed with exception #<RuntimeError: Application can be run by more than one container: Java Main, Spring Boot CLI> 
[STG] ERR Application can be run by more than one container: Java Main, Spring Boot CLI 
ERR Failed to compile droplet 
[STG] OUT Exit status 223
[STG] ERR Staging failed: Exited with status 2231

**Comment by sachkk76** [comment]
When we took off .groovy extension it worked. As part of groovy transform module I have java code which invokes the groovy file which has bunch functions wrapped up in class -
 class SomeClass{
	def someMethod(node){
		.. some code
	}
}
Looks like this is due to the Java build pack analysis of the artifact (.jar file) and the .groovy file(s) and how they are structured, the buildpack assumes the application needs to be deployed in a Groovy container.  After I renamed “script.groovy” to “script-groovy” to avoid the build pack adding the Groovy container, it started working.. Does it not allow to have the groovy file with class?

**Comment by sabbyanandan** [comment]
Glad to hear the registration issue is resolved. I will close this issue. 

For the (custom) groovy app issues, please review the [detection criteria](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/container-groovy.md). If you continue to have issues with it, perhaps you could open an issue in the `java-buildpack` repo.

**Comment by RamCharlapalli** [comment]
I have the similar issue and unable to launch the task from shell. Though I could successfully register the demo app and task, when I launch, it gives the following error. 

Command failed org.springframework.cloud.dataflow.rest.client.DataFlowClientException: failed to resolve MavenResource: com.example.demo:demo:jar:0.0.1-SNAPSHOT.jar. Configured remote repositories: springRepo,repo1

I am deploying the app from the local repo to data flow server. Can some one please help? here the command that I am using for app registration. 
dataflow:>app register --name batch-job --type task --uri maven://com.example.demo:demo:jar:0.0.1-SNAPSHOT.jar
Successfully registered application 'task:batch-job'

**Comment by ajkr195** [comment]
Hi RamCharlapalli, If you are doing it on your local machine then, try this:
app register --name batch-job --type task --uri file:///fully/qualified/local/parth/to/your/0.0.1-SNAPSHOT.jar
